apiVersion: v1
data:
  tls.crt: LS0aHZcGt........
  tls.key: LS0tL............
kind: Secret
metadata:
  creationTimestamp: "2026-09-21T21:35:17Z"
  name: tls-secret
  namespace: default
  resourceVersion: "760084"
  uid: dd71af03-5034-4b77-a576-222392745575
type: kubernetes.io/tls
